### ISSUE TITLE
EPUB exports missing key dependency after install

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/trellis#48]
After provisioning a local server with this repo, we see a `Some dependencies for EPUB exports could not be found. Please verify that you have completed the [installation instructions](https://pressbooks.org/user-docs/installation/).` message.
![Screenshot from 2022-09-21 07-02-09](https://user-images.githubusercontent.com/13485451/191525291-c164c10f-aee9-4128-9e73-f51d322572a6.png)
Christopher found that the epubcheck.jar file is installed on the server, just not in the expected location. 
```
[13:43:35] ^_^ apt-file list epubcheck
epubcheck: /usr/bin/epubcheck
epubcheck: /usr/share/doc/epubcheck/changelog.Debian.gz
epubcheck: /usr/share/doc/epubcheck/copyright
epubcheck: /usr/share/java/epubcheck-4.2.2.jar
epubcheck: /usr/share/java/epubcheck.jar
epubcheck: /usr/share/man/man1/epubcheck.1.gz
epubcheck: /usr/share/maven-repo/org/w3c/epubcheck/4.2.2/epubcheck-4.2.2.jar
epubcheck: /usr/share/maven-repo/org/w3c/epubcheck/4.2.2/epubcheck-4.2.2.pom
epubcheck: /usr/share/maven-repo/org/w3c/epubcheck/debian/epubcheck-debian.jar
epubcheck: /usr/share/maven-repo/org/w3c/epubcheck/debian/epubcheck-debian.pom
```
Simple local fix is 
```
sudo mkdir /opt/epubcheck
sudo ln -s /usr/share/java/epubcheck.jar /opt/epubcheck/epubcheck.jar
```

**Comment by cmurtagh** [comment]
Ok, I've updated trellis to create the symlink to the new location. Eventually we will update bedrocks to point to the location where the jar file is installed by the apt package.
